name: Release DuelScripts

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: build and release DuelScripts

    runs-on: ubuntu-latest

    steps:

      - name: Check out git repository
        uses: actions/checkout@v2
      
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: install dependencies
        run: yarn install

      - name: build project
        run: yarn build

      - name: zip files
        run: zip -r dist dist

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ubuntu-latest
          path: dist.zip

      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "dist.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}